### ISSUE TITLE
Entity not created for backoffice

### ISSUE THREAD

**Issue by KimBurgess** [PlaceOS/frontends#2]
The [implicit Backoffice clone and pull](https://github.com/PlaceOS/frontends/commit/07d950a47fa02941c60942981c1aa836905e3ee9) looks to run only on start, and does not create an associated repository in the DB. This prevents a deployment from pinning this to a specific release, as well as not having visibility of this from queries to the repositories endpoint.

This issue is more for discussion, rather than a bug / enhancement request - is this the correct behaviour?

**Comment by stakach** [comment]
There should be a base `www` repo (for nginx custom error pages etc) - backoffice doesn't need to be apart of this and we could have it as a default entry, not a difficult change. The current implementation is minimum viable product.

There should be a periodic pull of the `www` repo (I think once an hour)

**Comment by caspiano** [comment]
[backoffice is pulled here](https://github.com/PlaceOS/frontends/blob/master/src/frontends/loader.cr#L86)

**Comment by KimBurgess** [comment]
@caspiano, that looks to be just a pull. There's no repository model created, which means that it is not listed by the `/repositories` endpoint.

**Comment by caspiano** [comment]
I believe we are not explicitly creating a backoffice repository.

**Comment by stakach** [comment]
@KimBurgess it's not locked in stone though, open for discussion

**Comment by KimBurgess** [comment]
We should definitely provide a way of pinning this so that deploy state is not bound to an external variable. Default behaviour could be to follow HEAD on a primary repo, but having a supported / simple way to break from this will assist with test environments, along with ensuring that people involved in running deployed instances have control over what is updated, when.

Given that there's already a mechanism for this via the existing repositories management, this seems like a neat fix.

**Comment by caspiano** [comment]
Perhaps we should have an attribute to ensure that users cannot remove the backoffice repository, along the lines of a `protected` bool?

**Comment by stakach** [comment]
protected seems a bit much, need an init task so we can restore it / set it up initially
